name: "Formula 1 Addon"
description: "Addon per integrare informazioni Formula 1 in Home Assistant"
version: "1.0.0"
slug: "f1calendar_addon"
url: "https://github.com/domenicocarfora/f1calendar-addon"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: application
boot: auto
options:
  log_level: info
  update_interval: 3600
schema:
  log_level:
    type: select
    options:
      - fatal
      - error
      - warn
      - info
      - debug
      - trace
    default: info
    required: true
  update_interval:
    type: integer
    minimum: 300
    maximum: 86400
    default: 3600
    required: true
    unit: seconds
image: "ghcr.io/domenicocarfora/f1calendar-addon-{arch}"
host_network: false
host_pid: false
host_ipc: false
host_dbus: false
devices: []
auto_uart: false
map: []
tmpfs: []
environment:
  TZ: "Europe/Rome"

